### ISSUE TITLE
drop tl_formdata

### ISSUE THREAD

**Issue by reluem** [heimrichhannot/contao-fieldpalette#1] opened 2016-02-27 17:25 UTC
After installing **contao-fieldpalette** via composer on Contao 3.5.6, the database update suggests dropping tl_formdata_ (created by contao-legay/efg).
Dropping the table results in a recreation-drop loop...
Any suggestions on this? 

"contao-legacy/efg": ">=2.2.1.9005,<2.3-dev",
"contao-community-alliance/composer-client": "~0.12",
 "heimrichhannot/contao-fieldpalette": ">=1.0.1.0,<1.1-dev",

**Comment by fatcrobat** [comment] 2016-03-09 15:46
This seems to be fieldpalette unrelated, can you please disable the module by adding empty .skip file to system/modules/fieldpalette? Clear cache for sure after that and notify us if the drop table still remains?

**Comment by fatcrobat** [comment] 2016-03-23 10:03
This bug has been reproduced and will be fixed in 1.0.2

**Closed as completed** 2016-03-23 10:04 UTC
Labels: bug
